### ISSUE TITLE
Sharing iP code quality feedback [for @axmszr]

### ISSUE THREAD

**Issue by soc-se-bot-red** [axmszr/ip#5]
@axmszr We did an automated analysis of your code to detect potential areas to improve the code quality. We are sharing the results below, to help you improve the iP code further.

IMPORTANT: Note that the script looked for **just a few easy-to-detect problems only**, and **at-most three example are given** i.e., there can be other areas/places to improve.

### Aspect: Tab Usage

No easy-to-detect issues :+1: 

### Aspect: Naming boolean variables/methods

Example from [`src/main/java/cbot/Cbot.java` lines `23-23`](https://github.com/axmszr/ip/blob/169a95adc10ffee591c96050f30f9c5a6396be36/src/main/java/cbot/Cbot.java#L23..L23):

```java

    private boolean prevWasBad;

```

Example from [`src/main/java/cbot/io/Parser.java` lines `33-33`](https://github.com/axmszr/ip/blob/169a95adc10ffee591c96050f30f9c5a6396be36/src/main/java/cbot/io/Parser.java#L33..L33):

```java

        boolean matchFound = false;

```

Example from [`src/main/java/cbot/task/Task.java` lines `119-119`](https://github.com/axmszr/ip/blob/169a95adc10ffee591c96050f30f9c5a6396be36/src/main/java/cbot/task/Task.java#L119..L119):

```java

        boolean b = !this.isDone;

``` 

**Suggestion:** Follow the given naming convention for boolean variables/methods (e.g., use a boolean-sounding prefix).You may ignore the above if you think the name already follows the convention (the script can report false positives in some cases)

### Aspect: Brace Style

No easy-to-detect issues :+1: 

### Aspect: Package Name Style

No easy-to-detect issues :+1: 

### Aspect: Class Name Style

No easy-to-detect issues :+1: 

### Aspect: Dead Code

Example from [`src/main/java/cbot/task/TaskList.java` lines `15-15`](https://github.com/axmszr/ip/blob/169a95adc10ffee591c96050f30f9c5a6396be36/src/main/java/cbot/task/TaskList.java#L15..L15):

```java

    //private static final int GAPS = 3;

``` 

**Suggestion:** Remove dead code from the codebase.

### Aspect: Method Length

No easy-to-detect issues :+1: 

### Aspect: Class size

No easy-to-detect issues :+1: 

### Aspect: Header Comments

Example from [`src/main/java/cbot/task/Task.java` lines `41-45`](https://github.com/axmszr/ip/blob/169a95adc10ffee591c96050f30f9c5a6396be36/src/main/java/cbot/task/Task.java#L41..L45):

```java

    /**
     * Replace the current task description with a new description.
     *
     * @param newDesc The new task description.
     */

``` 

**Suggestion:** Ensure method/class header comments follow the format specified in the coding standard, in particular, the phrasing of the overview statement.

### Aspect: Recent Git Commit Message (Subject Only)

No easy-to-detect issues :+1: 

### Aspect: Binary files in repo

No easy-to-detect issues :+1: 

:information_source: The bot account used to post this issue is un-manned. **Do not reply to this post** (as those replies will not be read). Instead, contact `cs2103@comp.nus.edu.sg` if you want to follow up on this post.

**Comment by axmszr** [comment]
Went through the booleans but they all felt alright to me. Made the other changes. Thank you!
